imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@FloBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    session:
        name: "Flosite"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
                - 'bootstrap_3_layout.html.twig'


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Fos User Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: FloBundle\Entity\User

# Lexik Maintenance configuration
lexik_maintenance:
    authorized:
        path: /                                                             # Optional. Authorized path, accepts regexs
        ips: ['78.205.106.82', ]                                              # Optional. Authorized ip addresses

    driver:

         # File driver
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver'                # class for file driver
        options: {file_path: %kernel.root_dir%/cache/lock}                         # file_path is the complete path for create the file

         # Shared memory driver
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\ShmDriver'                 # class for shared memory driver

#         # MemCache driver
#        class: Lexik\Bundle\MaintenanceBundle\Drivers\MemCacheDriver               # class for MemCache driver
#        options: {key_name: 'maintenance', host: 127.0.0.1, port: 11211}           # need to define a key_name, the host and port

        # Database driver:
        class: 'Lexik\Bundle\MaintenanceBundle\Drivers\DatabaseDriver'             # class for database driver

        # Option 1 : for doctrine
        options: {connection: custom}                                            # Optional. You can choice an other connection. Without option it's the doctrine default connection who will be used

    #Optional. response code and status of the maintenance page
    response:
        code: 503
        status: "Service Temporarily Unavailable"

# Sonata SEO Configuration
sonata_seo:
    encoding:         UTF-8
    page:
        title:            Florence Menet-Pélisson
        default:          sonata.seo.page.default
        metas:
            name:
                keywords:             florence, menet, pelisson, dessin, contemporain, crayon, gravure sur bois, xylogravure, graphisme, gravure taille-douce, aquatinte, eau-forte, hybride, pointe seche, encre, estampe, crayon, dessin d'art, art, pastels, pastels secs, oeuvres sur papier, lecture, livres, romans, ecriture, fiction, arts plastiques, dessins d'enfants, cours 77, cours de dessin, seine et marne, stage de dessin, contraste, gouache, collage, couleurs
                description:          Le site de Florence Menet-Pelisson donne a voir les oeuvres sur papier (dessins au crayon, au pastel sec, gravures sur bois, gravures sur cuivre) de l'artiste ainsi que les travaux de ses eleves. La rubrique fiction presente ses lectures et les textes qu'elle-meme ecrit.
                robots:               index, follow
                google-site-verification: OmJpY2OE3wjHfUXSpWcf1liip8dsCtutluYVpM8TO6M

            property:
                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       Florence Menet-Pelisson
                'og:description':     Le site de Florence Menet-Pelisson donne a voir les oeuvres sur papier (dessins au crayon, au pastel sec, gravures sur bois, gravures sur cuivre) de l'artiste ainsi que les travaux de ses eleves. La rubrique fiction presente ses lectures et les textes qu'elle-meme ecrit.

            http-equiv:
                'Content-Type':         text/html;
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'lang':               fr
            'class':              no-js demo-4
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"



services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }


nomaya_social:
    buttons:
        facebook:
            url:            "http://www.florence-pelisson.fr/actualites"
            locale:         "fr_FR"
            send:           false
            width:          300
            showFaces:      true
            layout:         "button_count"
        twitter:
            url:            "http://www.florence-pelisson.fr/actualites"
            locale:         "fr"
            message:        "Je veux partager ça avec vous"
            text:           "Tweet"
            via:            null
            tag:            "art, expo"
        googleplus:
            url:            null
            locale :        "fr"
            size :          "medium"
            annotation :    "bubble"
            width :         300
        linkedin:
            url:            null
            locale:         "fr_FR"
            counter:        "right"
        pinterest:
            url:            null
    theme:                  'default' # optional

# CK Editor configuration
ivory_ck_editor:
    default_config:    my_config
    configs:
        my_config:
            toolbar:                   [ [ 'Bold','Italic','Underline','Strike', 'Blockquote','Subscript','Superscript' ], [ 'BulletedList', 'NumberedList','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ], [ 'Link','Unlink' ], [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ], ['SpellChecker', 'Scayt' ], [ 'Font','FontSize' ], [ 'TextColor','BGColor' ], [ 'RemoveFormat' ], [ 'Maximize' ] ]
            language: %locale%


liip_imagine:

    resolvers:
        default:
            web_path: ~
    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../web/uploads/images/"

    filter_sets:

        cache: ~

        # the name of the "filter set"
        my_thumb:
            # adjust the image quality to 75%
            quality: 40
            # list of transformations to apply (the "filters")
            filters:
                 relative_resize: { widen: 247 }

        img:
            quality: 75
            filters:
                  relative_resize: { widen: 1000 }


