#-----------------------------------------------------------------------------------------------------
#Appel route utilisateur/client
#-----------------------------------------------------------------------------------------------------

user_routing:
    resource: routing/user.yml
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


#-----------------------------------------------------------------------------------------------------
#Route accueil admin
#-----------------------------------------------------------------------------------------------------

admin_homepage:
    path:     /admin/
    defaults: { _controller: FloBundle:Default:admin }

#-----------------------------------------------------------------------------------------------------
#Appel route admin
#-----------------------------------------------------------------------------------------------------

flo_galerie:
    resource: "@FloBundle/Resources/config/routing/galerie.yml"
    prefix:   /admin/galerie

flo_cours:
    resource: "@FloBundle/Resources/config/routing/cours.yml"
    prefix:   /admin/cours

flo_categorie:
    resource: "@FloBundle/Resources/config/routing/categorie.yml"
    prefix:   /admin/categorie

flo_about:
    resource: "@FloBundle/Resources/config/routing/about.yml"
    prefix:   /admin/about

flo_actualites:
    resource: "@FloBundle/Resources/config/routing/actualites.yml"
    prefix:   /admin/actualites

#-----------------------------------------------------------------------------------------------------
#Route FosUserBundle
#-----------------------------------------------------------------------------------------------------

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#-----------------------------------------------------------------------------------------------------
#Route send mail
#-----------------------------------------------------------------------------------------------------

send_mail:
    path:     /mail
    defaults: { _controller: FloBundle:Default:send}
    methods: [GET, POST]
