FloBundle\Entity\Image:
    type: entity
    table: null
    repositoryClass: FloBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
            type: text
        dimensions:
            type: string
            length: 255
            nullable: true
        alt:
            type: string
            length: 255
            nullable: true

    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
