FloBundle\Entity\Image:
    type: entity
    table: null
    repositoryClass: FloBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        urls:
            type: array
