FloBundle\Entity\Modele:
    type: entity
    table: null
    repositoryClass: FloBundle\Repository\ModeleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        contenu:
            type: text
        liengaleriecours:
            type: string
            length: 255
            nullable: true

    manyToOne:
        categorie:
            targetEntity: FloBundle\Entity\Categorie
        image:
            targetEntity: FloBundle\Entity\Image
            cascade: ["persist", "remove"]

    lifecycleCallbacks: {  }
